[DSN-2][DSN-3][DSN-4][DSN-13] Project setup
celtra/design-system-next pull request #1
Opened 2021-05-21 10:59 UTC by Kemoke

2021-05-21 12:00 UTC, a42m requested changes

2021-05-21 13:16 UTC, Kemoke commented on yarn.lock
>  # yarn lockfile v1
Agreed to defer this to a later time.

2021-05-21 13:17 UTC, Kemoke commented on .storybook/preview.js
> +import DesignSystemNext from '../lib/index'
Aliases don't seem to work in this file.

2021-05-21 13:36 UTC, Kemoke commented on .storybook/preview.js
> +import DesignSystemNext from '../lib/index'
Nevermind it works.

2021-05-21 14:15 UTC, a42m approved these changes

2021-05-21 14:25 UTC, merged

2021-05-24 07:15 UTC, kurent commented on .stylelintrc
> +    "prettier/prettier": [true, {"singleQuote": true, "tabWidth": 4, "endOfLine": "auto"}]
yes, agreed